/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.ASchedule;
import database.IActivity;
import database.ITag;
import planat0r.Planator;

import java.awt.Checkbox;
import java.awt.Component;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JCheckBox;

/**
 *
 * @author ima3k
 */
public class ActivationsjFrame extends javax.swing.JFrame {

    List<IActivity> activities;
    List<IActivity> returnActivities;
    ArrayList<JCheckBox> checkboxes = new ArrayList<JCheckBox>();
    /**
     * Creates new form ActivationsjFrame
     */
    public ActivationsjFrame() {
        initComponents();
        
        activities = Planator.engine.generateActivities();
        
        createCheckboxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();        
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Proponowane aktywnosci");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));       

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()                
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jButton1.setText("next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    //next btn 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        generateMyActivities();
        runYourActivationsjFrame();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    void generateMyActivities() {
        //Date date = Date.parse( TextField2.getText() );
        //int money = Integer.parseInt( jTextField2.getText() );
        returnActivities = new ArrayList<IActivity>();                
        
        for (int i=0; i<checkboxes.size(); i++) {
            
            if (checkboxes.get(i).isSelected()) {              	   
                for (int j=0; j< activities.size(); j++) {                  	                   	  
                    if ( activities.get(j).getName().equals( checkboxes.get(i).getName() )) 
                    {                	  
                    	returnActivities.add( activities.get(j) );
                        break;
                    }
                }
            }           
         }
        
    }
    
    
    void runYourActivationsjFrame()
    {
        this.setVisible(false);
        this.dispose();               
                
        System.out.println("przed pobraniem planu linia 145 - plan sie nie zapisuje");
        ASchedule mySchedule = Planator.engine.submitActivties(returnActivities);
        System.out.println("po pobraniu planu");
        
        new YourActivationsJFrame( mySchedule ).setVisible(true);
    }
    
    JCheckBox checkbox;
    void createCheckboxes() {               
        
        jPanel1.setLayout(new GridBagLayout());
    	GridBagConstraints c = new GridBagConstraints();

    	int row = 0, rowMax = 3;
    	int column = 0;
        for (int i=0; i< activities.size(); i++) {
        	        	
            checkbox = new JCheckBox();  
            checkbox.setLabel(activities.get(i).getName());
            checkbox.setName(activities.get(i).getName());
            
            c.gridx = row++;
            c.gridy = column;
            
            if (row==rowMax) {
            	row = 0;
            	column++;
            }
            	
            jPanel1.add(checkbox,c);
            checkboxes.add(checkbox);
        }
    }
    
    /*public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActivationsjFrame().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
